---
- name: Copy AWS snapshot instance to a different AWS region
  hosts: localhost
  gather_facts: false
  vars:
    snapshot_id: ''
    region: us-east-1 # Region to copy snapshots
    source_region: us-west-2 # The source region the Snapshot should be copied from

  tasks:
      - name: Record the Date & time
        ansible.builtin.command:
          cmd: "date '+%D:%H:%M:%S'"
        delegate_to: 127.0.0.1
        register: ansible_date_time

      - name: Gather information about a particular snapshot using ID
        amazon.aws.ec2_snapshot_info:
          region: "{{ region }}"
#          filters:
#            snapshot-id: snap-00112233
        register: ec2_snap_info

      - name: Printing ALL Snapshots Information
        ansible.builtin.debug:
          msg:  "{{ ec2_snap_info }}"

#      - name: Copy Snapshot and wait until available
#        community.aws.ec2_snapshot_copy:
#          source_region: "{{ source_region }}"
#          region: "{{ region }}"
#          source_snapshot_id: "{{ ec2_snap_info }}"
#          wait: true
#          wait_timeout: 1200   # Default timeout is 600
#        register: snapshot_id
