---
- name: Create a GCP disk
  hosts: localhost
  connection: local
  vars:
    gcp_project: ''
    gcp_cred_kind: '' # serviceaccount
    disk_name: ''
    size_gb: ''
    gcp_zone: '' # us-central1-a #us-west2-a
    gcp_source_image: 'projects/rhel-cloud/global/images/rhel-9-1' # RHELv8 'projects/rhel-cloud/global/images/rhel-8-v20220406'
    rhel_version: ''

  tasks:

    - name: create a disk mapped from RHEL v"{{ rhel_version }}" image
      google.cloud.gcp_compute_disk:
        name: "{{ disk_name }}"
        size_gb: "{{ size_gb }}"
        source_image: "{{ gcp_source_image }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: "{{ state }}"
      register: disk

    - name: printing disk info
      debug:
        var: disk
