---
- name: Check Disk space and display results
  hosts: all
  vars:
     mount_all: []
     percentile: ""
     floating: ""
  tasks:
    - name: Get the right decimal
      set_fact:
        floating: "{{ percentile /100 }}"
    - name: Get List of devices higher than {{ percentile }}%
      set_fact:
        mount_all: "{{ mount_all + [{'host':ansible_host,'dev':item.device,'mount':item.mount,'free':(((item.size_available/1024)/1024)/1024)|round(2,'common'),'total':(((item.size_total/1024)/1024)/1024)|round(2,'common')}] }}"
      when: (item.size_total - item.size_available) > (item.size_total|float * 0.20)
      with_items: "{{ ansible_mounts | list }}"
      delegate_to: localhost

    - name: If partition is > 20%
      debug:
         msg: "{{ mount_all }} "